# Importing Dataset and other Important Libraries

In [88]:
# Importing Libraries

import pandas as pd
import numpy as np

from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler

from keras.models import Sequential
from keras.layers import Dense

In [3]:
# Loading Dataset in Notebook
# This dataset is the imported form data

data = load_breast_cancer()
data

{'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry \n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        largest values) of these features were computed for each image,\n        resulting in 30 features.  For

# Seeing other info of dataset

In [4]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
print(data.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [6]:
print(data.data)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [7]:
print(data.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [8]:
print(data.target_names)

['malignant' 'benign']


In [9]:
print(data.feature_names)

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [10]:
data.filename

'/usr/local/lib/python3.7/dist-packages/sklearn/datasets/data/breast_cancer.csv'

In [11]:
# It shows the first row

data.data[0]

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [12]:
# This shows the data along with their feature name and above considered row

j = 0
for i in data.feature_names:
  print(i, ":", data.data[0][j])
  j += 1

mean radius : 17.99
mean texture : 10.38
mean perimeter : 122.8
mean area : 1001.0
mean smoothness : 0.1184
mean compactness : 0.2776
mean concavity : 0.3001
mean concave points : 0.1471
mean symmetry : 0.2419
mean fractal dimension : 0.07871
radius error : 1.095
texture error : 0.9053
perimeter error : 8.589
area error : 153.4
smoothness error : 0.006399
compactness error : 0.04904
concavity error : 0.05373
concave points error : 0.01587
symmetry error : 0.03003
fractal dimension error : 0.006193
worst radius : 25.38
worst texture : 17.33
worst perimeter : 184.6
worst area : 2019.0
worst smoothness : 0.1622
worst compactness : 0.6656
worst concavity : 0.7119
worst concave points : 0.2654
worst symmetry : 0.4601
worst fractal dimension : 0.1189


# Defining Features and labels from the dataset

-> Features are like input which is used for further processing of data and it is also given to model.

-> Labels are like output which we expect from the model

In [13]:
features = data['data']
label = data['target']

In [14]:
features.shape

(569, 30)

In [15]:
label.shape

(569,)

In [16]:
scaled_features = StandardScaler()
features = scaled_features.fit_transform(features)

# Converting dataset into dataframe

In [17]:
# First of all we have to create Dataframe for features as well as for labels and 
# then merge / Concatenate those to make one Dataframe

df_feat = pd.DataFrame(columns=data['feature_names'], data=features)
df_lab  = pd.DataFrame(columns=['label'], data=label)

df = pd.concat([df_feat, df_lab], axis=1)
df.head()

mean radius  mean texture  ...  worst fractal dimension  label
0     1.097064     -2.073335  ...                 1.937015      0
1     1.829821     -0.353632  ...                 0.281190      0
2     1.579888      0.456187  ...                 0.201391      0
3    -0.768909      0.253732  ...                 4.935010      0
4     1.750297     -1.151816  ...                -0.397100      0

[5 rows x 31 columns]

In [18]:
# Checking for null values

df.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
label                      0
dtype: int64

In [19]:
# Seeing how much what we have in label coloumn

df.groupby(['label']).size()

label
0    212
1    357
dtype: int64

In [20]:
df.describe()

mean radius  mean texture  ...  worst fractal dimension       label
count  5.690000e+02  5.690000e+02  ...             5.690000e+02  569.000000
mean  -3.162867e-15 -6.530609e-15  ...             2.575171e-15    0.627417
std    1.000880e+00  1.000880e+00  ...             1.000880e+00    0.483918
min   -2.029648e+00 -2.229249e+00  ...            -1.601839e+00    0.000000
25%   -6.893853e-01 -7.259631e-01  ...            -6.919118e-01    0.000000
50%   -2.150816e-01 -1.046362e-01  ...            -2.164441e-01    1.000000
75%    4.693926e-01  5.841756e-01  ...             4.507624e-01    1.000000
max    3.971288e+00  4.651889e+00  ...             6.846856e+00    1.000000

[8 rows x 31 columns]

In [21]:
df

mean radius  mean texture  ...  worst fractal dimension  label
0       1.097064     -2.073335  ...                 1.937015      0
1       1.829821     -0.353632  ...                 0.281190      0
2       1.579888      0.456187  ...                 0.201391      0
3      -0.768909      0.253732  ...                 4.935010      0
4       1.750297     -1.151816  ...                -0.397100      0
..           ...           ...  ...                      ...    ...
564     2.110995      0.721473  ...                -0.709091      0
565     1.704854      2.085134  ...                -0.973978      0
566     0.702284      2.045574  ...                -0.318409      0
567     1.838341      2.336457  ...                 2.219635      0
568    -1.808401      1.221792  ...                -0.751207      1

[569 rows x 31 columns]

# Splitting Dataset for Training and Testing

In [79]:

#500 Training
X_train = features[:500]
y_train = label[:500]

#35 Validation
X_val = features[500:535]
y_val = label[500:535]

#34 Testing
X_test = features[535:]
y_test = label[535:]

# Model Building

In [81]:
model = Sequential()

model.add(Dense(32, activation = 'relu', input_dim = 30))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(128, activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(32, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

model.compile( loss = 'binary_crossentropy' , optimizer = 'adam' , metrics = ['accuracy'])

In [84]:
model.fit( X_train , y_train, epochs = 10, batch_size = 5, validation_data = (X_val, y_val))


Epoch 1/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0065 - accuracy: 0.9980 - val_loss: 0.1169 - val_accuracy: 0.9714
Epoch 2/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0043 - accuracy: 0.9980 - val_loss: 0.1832 - val_accuracy: 0.9714
Epoch 3/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0193 - accuracy: 0.9920 - val_loss: 0.1436 - val_accuracy: 0.9714
Epoch 4/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0077 - accuracy: 0.9980 - val_loss: 0.1103 - val_accuracy: 0.9714
Epoch 5/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0037 - accuracy: 1.0000 - val_loss: 0.1636 - val_accuracy: 0.9429
Epoch 6/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0176 - accuracy: 0.9960 - val_loss: 0.1345 - val_accuracy: 0.9714
Epoch 7/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0025 - accuracy: 1.0000 - val_loss: 0.1649 - val_accuracy: 0.9714
Epoch 

In [85]:
model.evaluate(X_test , y_test)


2/2 [==============================] - 0s 8ms/step - loss: 0.2916 - accuracy: 0.9706


[0.2915736734867096, 0.970588207244873]

In [86]:
model.evaluate(X_val , y_val)


2/2 [==============================] - 0s 8ms/step - loss: 0.1995 - accuracy: 0.9714


[0.19953753054141998, 0.9714285731315613]

In [95]:
for i in range(34):
  sample = X_test[i]
  sample = np.reshape(sample, (1,30))

  if (model.predict(sample)[0][0] > 0.5):
    print("-Benign")
  else:
    print("-Malignant")

  if (y_test[i] == 1):
    print("*Banign")
  else:
    print("*Melignant")
  print("-----------")

-Malignant
*Melignant
-----------
-Malignant
*Melignant
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Malignant
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Malignant
*Melignant
-----------
-Malignant
*Melignant
-----------
-Malignant
*Melignant
-----------
-Malignant
*Melignant
-----------
-Malignant
*Melignant
-----------
-Malignant
*Melignant
-----------
-Benign
*Banign
---------